version: '3'
services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-queue --queueHost 0.0.0.0 --queuePort 10001 --cert /data/127.0.0.1.pem --key /data/127.0.0.1-key.pem
    ports:
      # Queue Listening Host
      - "10001:10001"
    volumes:
      - ./azurite:/data
