### Create Document

PUT http://localhost:9200/library/_doc/1
Content-Type: application/json

{
  "title": "Norwegian Wood",
  "name": {
    "first": "Haruki",
    "last": "Murakami"
  },
  "publish_date": "1987-09-04T00:00:00+0900",
  "price": 19.95
}

### Create Document With Curl

curl --request PUT --url http://localhost:9200/library/_doc/1 --header 'content-type: application/json' --header 'user-agent: vscode-restclient' --data '{"title": "Norwegian Wood","name": {"first": "Haruki","last": "Murakami"},"publish_date": "1987-09-04T00:00:00+0900","price": 19.95}'

### Create Document 2

PUT http://localhost:9200/library/_doc/2
Content-Type: application/json

{
  "title": "INFO:DATA",
  "name": {
    "first": "Foo",
    "last": "Bar"
  },
  "publish_date": "1987-09-04T00:00:00+0900",
  "price": 19.95
}

### Create Document 2 With Curl

curl --request PUT --url http://localhost:9200/library/_doc/2 --header 'content-type: application/json' --header 'user-agent: vscode-restclient' --data '{"title": "INFO:DATA","name": {"first": "Foo","last": "Bar"},"publish_date": "1987-09-04T00:00:00+0900","price": 19.95}'

### Create Document 3

PUT http://localhost:9200/library/_doc/3
Content-Type: application/json

{
  "title": "INFO: DATA",
  "name": {
    "first": "Foo",
    "last": "Bar"
  },
  "publish_date": "1987-09-04T00:00:00+0900",
  "price": 19.95
}

### Create Document 3 With Curl

curl --request PUT --url http://localhost:9200/library/_doc/3 --header 'content-type: application/json' --header 'user-agent: vscode-restclient' --data '{"title": "INFO: DATA","name": {"first": "Foo","last": "Bar"},"publish_date": "1987-09-04T00:00:00+0900","price": 19.95}'

### Search Document

GET http://localhost:9200/library/_search

### Search Document With Curl

curl --request GET --url http://localhost:9200/library/_search --header 'user-agent: vscode-restclient'

### Search Document With Specified Word

GET http://localhost:9200/library/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "title": "INFO:"
    }
  }
}

### Search Document With Specified Word Using Curl

curl --request GET --url http://localhost:9200/library/_search --header 'content-type: application/json' --header 'user-agent: vscode-restclient' --data '{"query": {"match": {"title": "INFO:"}}}'

