@echo off
echo === Start cloc command

cloc-1.88.exe . ^
--by-file ^
--include-ext=go ^
--not-match-f=^.+_test.go$ ^
--exclude-content="Code generated by MockGen. DO NOT EDIT."

echo === End cloc command